<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8c15f4f7-c489-4747-a5ac-d472019b913c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanArchitectureLearnProject.WebAPI\CleanArchitectureLearnProject.WebAPI.csproj" />
  </ItemGroup>

</Project>
